<?php

namespace AppBundle\Repository\Maintenances;

/**
 * MaintenancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenancesRepository extends \Doctrine\ORM\EntityRepository
{
}
