<?php

namespace AppBundle\Repository\Maintenances;

/**
 * VerificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
