<?php

namespace AppBundle\Repository\Settings;

use Doctrine\ORM\EntityRepository;

/**
 * conventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConventionRepository extends EntityRepository
{
}
