<?php
namespace AppBundle\Repository\Settings;

use Doctrine\ORM\EntityRepository;

/**
 * PersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnelRepository extends EntityRepository
{
    public function findPersonnel ($annee,$annee2){
        
    $qb = $this->createQueryBuilder('p');
    
         $qb->Join('p.horairePrevi', 'h')
            ->addSelect('h')
            ->where('h.date >= :date_debut')
            ->andWhere('h.date <= :date_fin')
            ->groupBy('p.user')
            ->setParameters(array(
                'date_debut'    => $annee->format('Y-m-d'),
                'date_fin'      => $annee2->format('Y-m-d'),
            ));
         
    return $qb->getQuery()
              ->getResult();
    }
    
    public function findAllPersonnel (){
        
    $qb = $this->createQueryBuilder('p');
    
         $qb->groupBy('p.user');
         
    return $qb->getQuery()
              ->getResult();
    }
}
