<?php

namespace AppBundle\Repository\Settings;

/**
 * WorktimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorktimeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStartWorktime() {
        
        $qb = $this->createQueryBuilder('w');
        $date = new \DateTime();
        date_time_set($date,7,0,0);
        $qb->where('w.timeclock >= :date_now')
                 ->andWhere('w.direction = :direction')
                 ->setParameters(array(
                 'date_now' => date_format($date, 'Y-m-d'),
                 'direction' => 'startday'
                 ));

        return $qb->getQuery()->getResult();
    }
    
    public function findPeriodWorktime($datein,$dateout) {
        $qb = $this->createQueryBuilder('w');
        $qb->where('w.timeclock >= :datein')
                ->andWhere('w.timeclock <= :dateout')
                ->setParameters([
                    'datein' => $datein,
                    'dateout' => $dateout
                ]);

        return $qb->getQuery()->getResult();
    }
}
