security:

    encoders:
        UserBundle\Entity\User: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true

        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /evenement/calendrier
            logout:
                path: fos_user_security_logout
                target: /login
            remember_me:
                key:        %secret%
