<?php

namespace AppBundle\Repository\Events;

/**
 * BudgetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetsRepository extends \Doctrine\ORM\EntityRepository
{
}
