<?php

namespace AppBundle\Repository\Events;

use Doctrine\ORM\EntityRepository;

/**
 * HoraireEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorairesRepository extends EntityRepository
{
}
