<?php

namespace AppBundle\Repository\Events;

use Doctrine\ORM\EntityRepository;

/**
 * RepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasRepository extends EntityRepository
{
}
